---
title: "Mini-Project 2"
author: "Sichu Chuang & Yining Hua"
date: "October 31, 2017"
output: html_document
---

## Loading the data
This project looks for the relationship between the money and votes a candidate receives.


```{r, include=FALSE}
library(tidyverse)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


```{r}
#select useful variables for the candidate object.
#{id, name, state}
candi<-candidates%>%
  select(cand_id,cand_name,cand_state)
```

```{r}
#select useful variables for the committees object.
#{id, name, state}
commi<-committees%>%
  select(cmte_id,cmte_name,cmte_state)
```

```{r}
#select useful variables for the contributiona object.
#{candidates id, commitees id, transaction amount, entity type.}
contri = contributions%>%
  select(cmte_id,cand_id,state,transaction_amt,entity_type)
```


```{r}
#join the candi&commi&contri tables together by left_join()
fullTable = contri%>%
  left_join(candi, by="cand_id")%>%
  left_join(commi,by="cmte_id")%>%
  select(cand_name,transaction_amt,entity_type)
fullTable
```

Step 1: A plot of the relationship between the reveived contribution & votes of candidates.

```{r}
#Create a table for {candidate - votes}
vote <- left_join(house_elections, candidates, by = c("fec_id" = "cand_id"))%>%
  select(cand_name,general_votes,state)%>%arrange(desc(general_votes))%>%
  arrange(desc(general_votes))
vote
```


```{r}
#create a table for the of contributions each candidate receives
sumContri <- fullTable%>%
    group_by(cand_name)%>%
    summarize(sum_contri=sum(transaction_amt))%>%
    arrange(desc(sum_contri))

sumContri
```

```{r}
#The table for {candidate name - sum of contributions - general votes }
Cand_con_vo <- sumContri%>%
  full_join(vote, by="cand_name")%>%
  filter(!is.na(general_votes),!general_votes==0)%>%
  head(779)
Cand_con_vo
```

```{r}
#plotting the Cand_con_vo table
Cand_con_vo %>%
  ggplot(aes(x=sum_contri, y=general_votes))+
  geom_point()
```


```{r}
#A version without 2 extreme values
Cand_con_vo%>%
  filter(general_votes<750000)%>%
  ggplot(aes(x = sum_contri, y =general_votes),col = state)+
  geom_point( size = 1)+
  geom_smooth()
```

2.Specific looks at individual candidates.

```{r}

#A function comparing entity tapes of a candidate.
compare = function(name_arg){
  fullTable %>%
  filter(cand_name==name_arg)%>%
  group_by(entity_type)%>%
  summarize(sum=n_distinct(transaction_amt),amount=sum(transaction_amt))
}

```


```{r}
left_join(compare(name_arg="PIERLUISI, PEDRO R"),compare(name_arg = "OBAMA, BARACK"),by = "entity_type")

left_join(compare(name_arg="BENTIVOLIO, KERRY"),compare(name_arg = "BALDWIN, TAMMY"),by = "entity_type")

```








